live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
opacity = 1.0
startup_mode = "Windowed"
title = "Clacritty"
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 0
lines = 0