live_config_reload = true
import = ['~/.config/alacritty/catppuccin-mocha.yml']

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding = false
opacity = 0.7
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 0
y = 0
